spring:
    application:
        name: chat-service

server:
    port: ${BINAR_CHAT_SERVER_PORT:8082}

eureka:
    client:
        serviceUrl:
            defaultZone: ${BINAR_REGISTRY_SERVER:http://localhost:8761/eureka}
    instance:
        hostname: localhost
        prefer-ip-address: true