services:
  registry:
    image: binar-registry
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
  gateway:
    image: binar-gateway
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      - BINAR_REGISTRY_SERVER=http://registry:8761/eureka
      - BINAR_REGISTRY_SERVER_PORT=8761
      - BINAR_REGISTRY_SERVER_HOST=http://registry
  security:
    image: binar-security
    build:
      context: ./security
    ports:
      - "8081:8081"
    environment:
      - BINAR_REGISTRY_SERVER=http://registry:8761/eureka
      - BINAR_SECURITY_DB_HOST=dbpg
      - BINAR_SECURITY_DB_PORT=5432
      - BINAR_SECURITY_DB_NAME=securitydb
      - BINAR_SECURITY_DB_USERNAME=postgres
      - BINAR_SECURITY_DB_PASSWORD=DbPassword
      - BINAR_SECURITY_JWT_SECRET_KEY=
      - BINAR_SECURITY_JWT_EXPIRATION_TIME=
      - BINAR_SECURITY_JWT_REFRESH_TOKEN_SECRET_KEY=
      - BINAR_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_TIME=
      - BINAR_SECURITY_OAUTH2_GOOGLE_CLIENT_ID=
      - BINAR_SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET=
      - BINAR_SECURITY_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  chat:
    image: binar-chat
    build:
      context: ./chat
    ports:
      - "8082:8082"
    environment:
      - BINAR_REGISTRY_SERVER=http://registry:8761/eureka
  binarfud:
    image: binar-fud
    build:
      context: ./binarfud
    ports:
      - "8083:8083"
    environment:
      - BINAR_REGISTRY_SERVER=http://registry:8761/eureka
      - BINARFUD_DB_HOST=dbpg
      - BINARFUD_DB_PORT=5432
      - BINARFUD_DB_NAME=binarfuddb
      - BINARFUD_DB_USERNAME=postgres
      - BINARFUD_DB_PASSWORD=DbPassword
      - BINARFUD_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  notifier:
    image: binar-notifier
    build:
      context: ./notifier
    ports:
      - "8089:8089"
    environment:
      - BINAR_NOTIFIER_MAIL_HOST=
      - BINAR_NOTIFIER_MAIL_PORT=
      - BINAR_NOTIFIER_MAIL_USERNAME=
      - BINAR_NOTIFIER_MAIL_PASSWORD=
      - BINAR_NOTIFIER_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BINAR_NOTIFIER_FIREBASE_CREDENTIALS_PATH=/app/key/firebase-adminsdk.json
    volumes:
      - ./file/firebase-adminsdk.json:/app/key/firebase-adminsdk.json
  fcm-demo:
    image: fcm-demo
    build:
      context: ./FCM-demo
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_API_KEY=
      - VITE_APP_AUTH_DOMAIN=
      - VITE_APP_PROJECT_ID=
      - VITE_APP_STORAGE_BUCKET=
      - VITE_APP_MESSAGING_SENDER_ID=
      - VITE_APP_APP_ID=
      - VITE_APP_MEASUREMENT_ID=
      - VITE_APP_VAPID_KEY=
  dbpg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DbPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./file/init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    user: root
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:
