server:
    port: ${BINARFUD_SERVER_PORT}
    servlet:
        context-path: /binarfud

spring:
    application:
        name: binarfud-service
    datasource:
        url: jdbc:postgresql://${BINARFUD_DB_HOST}:${BINARFUD_DB_PORT}/${BINARFUD_DB_NAME}
        username: ${BINARFUD_DB_USERNAME}
        password: ${BINARFUD_DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: ${BINARFUD_KAFKA_BOOTSTRAP_SERVERS}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        prefer-ip-address: true