server:
    port: ${BINARFUD_NOTIFIER_PORT:8587}

spring:
    application:
        name: notifier-service
    mail:
        host: ${BINARFUD_MAIL_HOST}
        port: ${BINARFUD_MAIL_PORT}
        username: ${BINARFUD_MAIL_USERNAME}
        password: ${BINARFUD_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        bootstrap-servers: ${BINARFUD_KAFKA_BOOTSTRAP_SERVERS}