spring:
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${BINAR_REGISTRY_SERVER:http://localhost:8761/eureka}
    instance:
        hostname: localhost
        prefer-ip-address: true