spring:
    application:
        name: chat-service

server:
    port: 8082

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
        prefer-ip-address: true