server:
    port: ${BINAR_SECURITY_SERVER_PORT:8081}

spring:
    application:
        name: security-service
        security:
            jwt:
                secret-key: ${BINAR_SECURITY_JWT_SECRET_KEY}
                expiration-time: ${BINAR_SECURITY_JWT_EXPIRATION_TIME}
                refresh-token:
                    secret-key: ${BINAR_SECURITY_JWT_REFRESH_TOKEN_SECRET_KEY}
                    expiration-time: ${BINAR_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_TIME}
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${BINAR_SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
                        client-secret: ${BINAR_SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}
                        redirect-uri: ${BINAR_SECURITY_BASEURL:${baseUrl}}/login/oauth2/code/google
    datasource:
        url: jdbc:postgresql://${BINAR_SECURITY_DB_HOST}:${BINAR_SECURITY_DB_PORT}/${BINAR_SECURITY_DB_NAME}
        username: ${BINAR_SECURITY_DB_USERNAME}
        password: ${BINAR_SECURITY_DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        property-naming-strategy: SNAKE_CASE
    kafka:
        bootstrap-servers: ${BINAR_SECURITY_KAFKA_BOOTSTRAP_SERVERS}

eureka:
    client:
        serviceUrl:
            defaultZone: ${BINAR_REGISTRY_SERVER:http://localhost:8761/eureka}
    instance:
        hostname: localhost
        prefer-ip-address: true